name: Main worlflow

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Allow unprivileged user namespaces (for Ubuntu 24.04)
        run: |
          sudo sysctl kernel.apparmor_restrict_unprivileged_userns=0

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install attr mergerfs
          curl -L -o /tmp/try-latest.tgz https://github.com/binpash/try/releases/download/latest/try-latest.tgz
          tar -xzf /tmp/try-latest.tgz -C "$HOME"
          cd "$HOME/try-0.2.0"
          ./configure
          make
          sudo make install
          try --version

      - name: Build
        run: gcc reproduction.c -o reproduction

      - name: Test
        run: try ./reproduction
